### ISSUE TITLE
One iterator per transaction means concurrent queries don't run over the same snapshot

### ISSUE THREAD

**Issue by ghost** [jpincas/tormenta#12]
I recall reading about this maybe being fixed on the badgerdb commit list 

Otherwise ask the main committer. He is very helpful about these things !

**Comment by jpincas** [comment]
If you use manual transactions, you can't have more than one iterator going per transactions, so at the moment, concurrent queries do not run all in the same transaction.

**Comment by ghost** [comment]
The reason I bring this all up is because i think it's possible to make this work client server also, as well as embedded !.
Client server can just wrap embedded using grpc. Quite easy.
But the concurrency stuff just needs to be overcome first.

Would be nice.

**Comment by jpincas** [comment]
When you say 'concurrency stuff', what exactly do you mean? Are you referring to the same issue I mentioned above (only 1 open iterator per transaction)?

**Comment by ghost** [comment]
Yes the one iterator per transaction aspect.

This all comes under the area of linearizability as they call it.
Have you got a good handle on what is and is not linearizable yet ??

**Comment by jpincas** [comment]
Ok, cool, we're talking about the same thing.  I'll change the title of this issue so we can keep a handle on it better.

To answer your question: I have no idea what that means.

**Comment by ghost** [comment]
Look it up on Google. It's exactly what you want.

**Comment by ghost** [comment]
It all about database serialisation

**Comment by ghost** [comment]
I just wanted to get a clear idea of the edge cases.
Jespen database testing.. 

https://www.informationweek.com/database/the-man-who-tortures-databases/d/d-id/1111407

**Comment by jpincas** [comment]
To be honest, that kind of stuff is over my head.  I'm a web dev by background: I started Tormenta because there was nothing out there that fitted what I really wanted, but quickly found that I was out of my depth. I'm doing my best to pick up 'lower level' skills, but without the technical or CS background, it's hard going!!

**Comment by jpincas** [comment]
This is not an issue any more. I've rewritten the core querying functionality and also realised that the Badger iterator restriction doesn't apply to read-only transactions and I was accidentally opening transactions in RW mode.
