### ISSUE TITLE
graphql

### ISSUE THREAD

**Issue by ghost** [jpincas/tormenta#3]
you have ton a ton of work on this.

I saw the query builder. Its really good!. But joins etc is a huge amount of work.
If you used GraphQL then you would get a query language for free that support joins.
It does Codegen f your types. Not Message Pack.
https://github.com/99designs/gqlgen

It solves a pretty big problem for this project. Have a think about it and grab me if you want to discuss.

**Comment by jpincas** [comment]
Hey man - that's an interesting idea - I need to do some thinking about the implications.  I actually just started turning my attention back to this project this weekend as Im going to use Tormenta in new project - so this is good timing.

Could you detail a bit more where you see graphql fitting in?  I looked at gqlgen and as its a schema-first approach, I'm not sure how that gels with Tormenta, which just gives you a fairly simple persistence layer for your Go structs.

On the other hand, perhaps Tormenta could be used as a simple persistence layer for gqlgen projects, or something like that?

**Comment by jpincas** [comment]
Closing as no reply from OP

**Comment by ghost** [comment]
@jpincas

Sorry was away.

You stuck on the design ?

You can also codegen the graphql from the data base schema using reflection over your badger buckets.

Gglgen I think can easily do that.

Does that help ???

**Comment by jpincas** [comment]
Sorry.  I'm still totally unclear as to what you are proposing.
